import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 3s infinite',
        'blob': 'blob 7s infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        }
      },
      colors: {
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          900: '#134e4a',
          950: '#042f2e',
        },
        dark: {
          900: '#0B0C10',
          800: '#1F2833',
          700: '#2C3A47',
        },
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#ef9900",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary": "#ffffff",
        "primary-container": "rgb(var(--c-primary-container) / <alpha-value>)",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#002113",
        "surface-tint": "rgb(var(--c-surface-tint) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "on-primary-fixed": "#00164e",
        tertiary: "#3e2400",
        "surface-bright": "rgb(var(--c-surface-bright) / <alpha-value>)",
        "tertiary-container": "#5c3800",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "secondary-container": "#6cf8bb",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        "on-secondary-container": "#00714d",
        "surface-container-highest": "rgb(var(--c-surface-container-highest) / <alpha-value>)",
        "on-error": "#ffffff",
        "inverse-surface": "rgb(var(--c-inverse-surface) / <alpha-value>)",
        secondary: "#006c49",
        "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "inverse-primary": "#b6c4ff",
        "surface-container-lowest": "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#264191",
        "on-primary-container": "rgb(var(--c-on-primary-container) / <alpha-value>)",
        "tertiary-fixed": "#ffddb8",
        background: "rgb(var(--c-background) / <alpha-value>)",
        error: "#ba1a1a",
        "surface-container-high": "rgb(var(--c-surface-container-high) / <alpha-value>)",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "rgb(var(--c-on-background) / <alpha-value>)",
        "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
        "primary-fixed-dim": "#b6c4ff",
        "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "rgb(var(--c-inverse-on-surface) / <alpha-value>)",
        outline: "rgb(var(--c-outline) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "20px",
        xl: "32px",
        "margin-desktop": "40px",
        md: "16px",
        xs: "8px",
        "margin-mobile": "16px",
        lg: "24px",
        sm: "12px",
        base: "4px",
      },
      maxWidth: {
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "numeric-data": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeric-data": ["20px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
