import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#757682",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#ef9900",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#002113",
        "surface-tint": "#4059aa",
        "on-surface-variant": "#444651",
        "on-primary-fixed": "#00164e",
        tertiary: "#3e2400",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#5c3800",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#6cf8bb",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        surface: "#f8f9ff",
        "on-secondary-container": "#00714d",
        "surface-container-highest": "#d3e4fe",
        "on-error": "#ffffff",
        "inverse-surface": "#213145",
        secondary: "#006c49",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "inverse-primary": "#b6c4ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#264191",
        "on-primary-container": "#90a8ff",
        "tertiary-fixed": "#ffddb8",
        background: "#f8f9ff",
        error: "#ba1a1a",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#b6c4ff",
        "outline-variant": "#c5c5d3",
        primary: "#00236f",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#eaf1ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "20px",
        xl: "32px",
        "margin-desktop": "40px",
        md: "16px",
        xs: "8px",
        "margin-mobile": "16px",
        lg: "24px",
        sm: "12px",
        base: "4px",
      },
      maxWidth: {
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "numeric-data": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeric-data": ["20px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
